In [2]:
import numpy as np
import pandas as pd
from sklearn.utils import shuffle

In [3]:
train_df = pd.read_csv('../../data/fixed_data/ResultTrain_FixedData.csv')
train_df

,Photo Name,Concentration,Area,Min distance,Mean distance,Max distance,Standart deviation
0,30104,12.5,459595.808626,0,18.851519,39,9.531099
1,31248,12.5,387228.811245,0,60.957377,95,22.078680
2,30924,12.5,424319.520705,0,52.869520,83,17.748318
3,50159,12.5,411692.058862,0,9.624227,21,4.230352
4,50126,12.5,434205.382150,0,21.305216,36,7.126810
...,...,...,...,...,...,...,...
7234,30501,50.0,362070.133534,0,3.032832,19,3.219556
7235,30366,50.0,418539.450006,0,43.237500,80,18.886183
7236,20180,50.0,348555.470605,0,21.665083,37,8.419914
7237,30151,50.0,439799.078196,0,55.356151,78,19.496467
7238,40942,50.0,534180.684486,0,66.465181,101,27.793140

In [4]:
train_df = shuffle(train_df)
train_df

,Photo Name,Concentration,Area,Min distance,Mean distance,Max distance,Standart deviation
865,31235,12.5,3.803223e+05,0,76.936556,121,29.205922
2766,10786,25.0,6.093999e+05,0,26.874753,39,6.366602
2780,41653,25.0,1.600203e+05,0,5.689587,13,2.480951
3128,11103,0.0,1.026809e+06,0,20.519940,55,12.571114
3446,11206,0.0,9.736353e+05,0,12.004078,28,5.178461
...,...,...,...,...,...,...,...
5706,20110,75.0,2.291563e+05,0,10.457189,23,5.592173
3313,40076,0.0,4.272154e+05,0,21.282887,37,6.478428
4972,11324,96.0,1.449771e+05,0,14.286561,25,5.359312
3268,10488,0.0,9.006350e+05,0,10.230375,20,4.694761
4157,11841,96.0,2.031839e+05,0,1.985158,5,1.390320

In [5]:
test_df = pd.read_csv('../../data/fixed_data/ResultTest_FixedData.csv')
test_df

,Photo Name,Concentration,Area,Min distance,Mean distance,Max distance,Standart deviation
0,20864,12.5,91621.680685,0,9.046512,17,3.204955
1,20778,12.5,110081.220131,0,6.319149,15,3.309816
2,20552,12.5,478240.730579,0,20.760296,38,6.440581
3,20913,12.5,83725.082797,0,22.042155,30,5.241976
4,20707,12.5,19678.020928,0,2.907514,6,1.304772
...,...,...,...,...,...,...,...
2994,50164,50.0,4145.556647,0,3.483516,9,2.160396
2995,50152,50.0,11773.917141,0,4.617021,9,2.236574
2996,50105,50.0,460895.602467,0,37.492291,63,15.561550
2997,50445,50.0,310270.142216,0,5.394030,10,2.480364
2998,50111,50.0,475633.712495,0,44.111575,70,15.097219

In [6]:
test_df = shuffle(train_df)
test_df

,Photo Name,Concentration,Area,Min distance,Mean distance,Max distance,Standart deviation
4029,10681,96.0,236538.482741,0,13.801887,26,7.694954
2474,30210,25.0,616072.996644,0,14.419261,27,5.398723
4404,20200,96.0,258803.261561,0,9.032659,21,4.817722
4070,10089,96.0,149376.014602,0,1.965293,4,1.261343
5990,20429,75.0,196006.262707,0,0.982890,2,0.665337
...,...,...,...,...,...,...,...
6831,40486,50.0,504808.572690,0,43.056950,71,15.997214
4375,20355,96.0,192667.733716,0,2.371429,6,1.605094
1987,10509,25.0,610931.658018,0,10.412890,22,5.236089
3478,11393,0.0,974558.709986,0,17.796266,41,7.531636
4540,20012,96.0,218610.737846,0,6.286213,13,2.978416

In [7]:
X_train = train_df.drop(['Concentration','Photo Name'], axis=1)
X_train

,Area,Min distance,Mean distance,Max distance,Standart deviation
865,3.803223e+05,0,76.936556,121,29.205922
2766,6.093999e+05,0,26.874753,39,6.366602
2780,1.600203e+05,0,5.689587,13,2.480951
3128,1.026809e+06,0,20.519940,55,12.571114
3446,9.736353e+05,0,12.004078,28,5.178461
...,...,...,...,...,...
5706,2.291563e+05,0,10.457189,23,5.592173
3313,4.272154e+05,0,21.282887,37,6.478428
4972,1.449771e+05,0,14.286561,25,5.359312
3268,9.006350e+05,0,10.230375,20,4.694761
4157,2.031839e+05,0,1.985158,5,1.390320

In [8]:
y_train = train_df[train_df.columns[1]].astype('int')
y_train

865     12
2766    25
2780    25
3128     0
3446     0
        ..
5706    75
3313     0
4972    96
3268     0
4157    96
Name: Concentration, Length: 7239, dtype: int64

In [9]:
X_test = test_df.drop(['Concentration', 'Photo Name'], axis=1)
X_test

,Area,Min distance,Mean distance,Max distance,Standart deviation
4029,236538.482741,0,13.801887,26,7.694954
2474,616072.996644,0,14.419261,27,5.398723
4404,258803.261561,0,9.032659,21,4.817722
4070,149376.014602,0,1.965293,4,1.261343
5990,196006.262707,0,0.982890,2,0.665337
...,...,...,...,...,...
6831,504808.572690,0,43.056950,71,15.997214
4375,192667.733716,0,2.371429,6,1.605094
1987,610931.658018,0,10.412890,22,5.236089
3478,974558.709986,0,17.796266,41,7.531636
4540,218610.737846,0,6.286213,13,2.978416

In [10]:
y_test = test_df[test_df.columns[1]].astype('int')
y_test

4029    96
2474    25
4404    96
4070    96
5990    75
        ..
6831    50
4375    96
1987    25
3478     0
4540    96
Name: Concentration, Length: 7239, dtype: int64

In [13]:
from sklearn.model_selection import GridSearchCV

In [14]:
from sklearn.naive_bayes import GaussianNB

In [16]:
nb_classifier = GaussianNB()

params_NB = {'var_smoothing': np.logspace(0,-9, num=100)}
GaussianNB_model = GridSearchCV(estimator=nb_classifier, 
                 param_grid=params_NB, 
                 cv=7,   # use any cross validation technique 
                 verbose=1, 
                 scoring='accuracy') 
GaussianNB_model.fit(X_train,y_train)

Fitting 7 folds for each of 100 candidates, totalling 700 fits

GridSearchCV(cv=7, estimator=GaussianNB(),
             param_grid={'var_smoothing': array([1.00000000e+00, 8.11130831e-01, 6.57933225e-01, 5.33669923e-01,
       4.32876128e-01, 3.51119173e-01, 2.84803587e-01, 2.31012970e-01,
       1.87381742e-01, 1.51991108e-01, 1.23284674e-01, 1.00000000e-01,
       8.11130831e-02, 6.57933225e-02, 5.33669923e-02, 4.32876128e-02,
       3.51119173e-02, 2.84803587e-02, 2.31...
       1.23284674e-07, 1.00000000e-07, 8.11130831e-08, 6.57933225e-08,
       5.33669923e-08, 4.32876128e-08, 3.51119173e-08, 2.84803587e-08,
       2.31012970e-08, 1.87381742e-08, 1.51991108e-08, 1.23284674e-08,
       1.00000000e-08, 8.11130831e-09, 6.57933225e-09, 5.33669923e-09,
       4.32876128e-09, 3.51119173e-09, 2.84803587e-09, 2.31012970e-09,
       1.87381742e-09, 1.51991108e-09, 1.23284674e-09, 1.00000000e-09])},
             scoring='accuracy', verbose=1)

In [17]:
pred_train_GaussianNB = GaussianNB_model.predict(X_test)

In [18]:
from sklearn.metrics import classification_report

In [19]:
print(classification_report(y_test.values, pred_train_GaussianNB))

              precision    recall  f1-score   support

           0       0.83      0.88      0.86       978
          12       0.62      0.85      0.72      1712
          25       0.86      0.62      0.72      1098
          50       0.70      0.05      0.09       814
          75       0.14      0.04      0.06      1148
          96       0.50      0.90      0.64      1489

    accuracy                           0.61      7239
   macro avg       0.61      0.56      0.51      7239
weighted avg       0.59      0.61      0.55      7239

In [21]:
param_grid = {'bootstrap': [True, False],
              'max_depth': [10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 110],
              'max_features': ['auto', 'sqrt'],
              'min_samples_leaf': [1, 2, 4],
              'min_samples_split': [2, 5, 10],
              'n_estimators': [200, 400, 600, 800, 1000, 1200, 1400, 1600, 1800, 2000]}

In [22]:
from sklearn.ensemble import RandomForestClassifier

In [27]:
RandomForestClassifier_model = RandomForestClassifier()
RF = GridSearchCV(estimator = RandomForestClassifier_model, 
                                            param_grid = param_grid, 
                                            cv = 3, 
                                            n_jobs = -1, 
                                            verbose = 1)
RF.fit(X_train, y_train)

Fitting 3 folds for each of 3960 candidates, totalling 11880 fits

KeyboardInterrupt: